// <auto-generated />
using System;
using Johan_Reinoso_AP1_P2.Components.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Johan_Reinoso_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250714233908_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Johan_Reinoso_AP1_P2.Components.Models.Entradas", b =>
                {
                    b.Property<int>("EntradasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradasId"));

                    b.Property<double>("CantidadProducida")
                        .HasColumnType("float");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducido")
                        .HasColumnType("int");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("float");

                    b.HasKey("EntradasId");

                    b.ToTable("entradas");
                });

            modelBuilder.Entity("Johan_Reinoso_AP1_P2.Components.Models.EntradasDetalles", b =>
                {
                    b.Property<int>("EntradasDetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradasDetallesId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EntradasId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradasDetallesId");

                    b.HasIndex("EntradasId");

                    b.HasIndex("ProductoId");

                    b.ToTable("entradasDetalles");
                });

            modelBuilder.Entity("Johan_Reinoso_AP1_P2.Components.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("bit");

                    b.Property<int>("Existencias")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("ProductoId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Johan_Reinoso_AP1_P2.Components.Models.EntradasDetalles", b =>
                {
                    b.HasOne("Johan_Reinoso_AP1_P2.Components.Models.Entradas", "Entrada")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("EntradasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Johan_Reinoso_AP1_P2.Components.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Johan_Reinoso_AP1_P2.Components.Models.Entradas", b =>
                {
                    b.Navigation("VentasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
